### PR TITLE
Add extra template options and improve test coverage

### PR DESCRIPTION
**Pull request by willejs**
Hey, I was going to write exactly this, so you have saved me a job!
I've added some extra template options as I plan to use this with Azure.
Whilst doing this I am going to improve the test coverage, and clean up the cookbook a bit.

Tasks:
- [x] Refactor source install to converge correctly under ubuntu
- [x] Add a simple integration test to check the binary compiles and is executable
- [x] Fix all rubocop errors
- [x] Fix all food critic errors
- [x] Add extra_ops template options
- [x] Test extra_ops template options
- [x] Write some unit tests to validate logic in source/binary install
- [x] Add suite and fixture cookbook to test custom resource

### CODE REVIEW

**Comment by willejs** [comment]
@JonathanSerafini what are your thoughts?
Im going to add some chefspec tests tomorrow morning...

**Comment by willejs** [comment]
@failshell I think your part of lightspeedretail too, can you have a look at this please?

**Comment by willejs** [comment]
@JonathanSerafini @failshell i dont really want to fork this, can you review?
I was going to refactor install to a custom resource too...

**Comment by willejs** [comment]
@pieter-vanisacker @hartfordfive can you help?

**Comment by JonathanSerafini** [comment]
Hi @willejs, looked at the PR real quick and it seems good (thanks for that btw!).

I've been on vacation for the last month so I'm a bit short for time at present, but i'll give this a more thorough look-over early next week.

**Comment by willejs** [comment]
Cheers @JonathanSerafini 
Sorry for hassling everyone!

**Comment by JonathanSerafini** [comment]
@willejs Just merged the PR, looks awesome thank you ! 
No worries at all, I know too well that it's like getting no response and it's not very fun. 

Given that others seem to find this helpful as well, we likely should at renaming the cookbook so that it may be uploaded to supermarket. I'm thinking potentially of go_oauth2_proxy or some such. Any preferences ?

**Pull request merged**
